# docker-compose.yml
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: fiscaliza_cda
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
  api:
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - db
